// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// LOGOUT
export const LOGOUT = "LOGOUT";

// FETCH MOVIE
export const FETCH_MOVIE_START = "FETCH_MOVIE_START";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";
// CREATE MOVIE
export const CREATE_MOVIE_START = "CREATE_MOVIE_START";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAILURE = "CREATE_MOVIE_FAILURE";
// UPDATE MOVIE
export const UPDATE_MOVIE_START = "UPDATE_MOVIE_START";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAILURE = "UPDATE_MOVIE_FAILURE";
// DELETE MOVIE
export const DELETE_MOVIE_START = "DELETE_MOVIE_START";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE";